spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: todo
    password: todo
    initialization-mode: always
  h2:
    console:
      enabled: true
