-- TASK
CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    DETAIL VARCHAR(255),
    EXECUTION_DATE TIMESTAMP,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    COMPLETE_FLG CHAR(1) NOT NULL DEFAULT '0'
);


-- SUB_TASK
CREATE TABLE IF NOT EXISTS SUB_TASK (
    TASK_ID INT NOT NULL,
    SUB_TASK_ID INT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DETAIL VARCHAR(255),
    EXECUTION_DATE TIMESTAMP,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    COMPLETE_FLG CHAR(1) NOT NULL DEFAULT '0',
    PRIMARY KEY(TASK_ID, SUB_TASK_ID)
);


CREATE TABLE IF NOT EXISTS TEST (
  id  IDENTITY ,
  name VARCHAR(255)
);