-- TASK
CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    DETAIL VARCHAR(255),
    EXECUTION_DATE TIMESTAMP,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP
);


-- SUB_TASK
CREATE TABLE IF NOT EXISTS SUB_TASK (
    TASK_ID INT NOT NULL,
    SUB_TASK_ID INT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DETAIL VARCHAR(255),
    EXECUTION_DATE TIMESTAMP,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    PRIMARY KEY(TASK_ID, SUB_TASK_ID)
);


-- NEXT_SUB_TASK
CREATE TABLE IF NOT EXISTS NEXT_SUB_TASK (
    TASK_ID INT NOT NULL,
    SUB_TASK_ID INT NOT NULL,
    NEXT_SUB_TASK_ID INT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DETAIL VARCHAR(255),
    EXECUTION_DATE TIMESTAMP,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    PRIMARY KEY(TASK_ID, SUB_TASK_ID, NEXT_SUB_TASK_ID)
);
